version: "3.9"

services:
    postgres:
        restart: always
        container_name: PostgresEmployeeSection
        image: postgres:latest
        environment:
            POSTGRES_DB: "EmployeeSectionDb"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 10s
            retries: 5
            start_period: 30s
            timeout: 10s
        ports:
            - "5432:5432"
        networks:
            net:
                ipv4_address: 172.77.1.2

    api:
        depends_on:
            postgres:
                condition: service_healthy
                restart: true
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: EmployeeSection.API
        ports:
            - "8080:8080"
        networks:
            net:
                ipv4_address: 172.77.1.3

networks:
    net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.77.1.0/24
                  gateway: 172.77.1.1  
        